// Destinations data — lat/lon used by 3D globe, plus rich card metadata.
export const destinations = [
  {
    id: 'kyoto',
    name: 'Kyoto',
    country: 'Japan',
    region: 'Asia',
    tagline: 'Temples, lanterns and the slow hush of bamboo.',
    coords: { lat: 35.0116, lon: 135.7681 },
    color: '#FF7A00',
    image: 'https://images.unsplash.com/photo-1545569310-3f4c92cf6f87?auto=format&fit=crop&w=1600&q=80',
    days: 9,
    fromPrice: 4900,
    accent: 'ember',
  },
  {
    id: 'patagonia',
    name: 'Patagonia',
    country: 'Chile',
    region: 'South America',
    tagline: 'Granite spires, glacial lakes, and the wind that carved them.',
    coords: { lat: -49.3, lon: -73.0 },
    color: '#7fb89c',
    image: 'https://images.unsplash.com/photo-1531219432768-9f540ec08b81?auto=format&fit=crop&w=1600&q=80',
    days: 12,
    fromPrice: 7400,
    accent: 'forest',
  },
  {
    id: 'marrakech',
    name: 'Marrakech',
    country: 'Morocco',
    region: 'Africa',
    tagline: 'Spice markets, riads and a desert that never quite sleeps.',
    coords: { lat: 31.6295, lon: -7.9811 },
    color: '#FFAA57',
    image: 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1600&q=80',
    days: 7,
    fromPrice: 3200,
    accent: 'ember',
  },
  {
    id: 'iceland',
    name: 'Iceland',
    country: 'Iceland',
    region: 'Europe',
    tagline: 'Black beaches, geothermal mist, and the aurora.',
    coords: { lat: 64.1265, lon: -21.8174 },
    color: '#b3d6c3',
    image: 'https://images.unsplash.com/photo-1531168556467-80aace0d0144?auto=format&fit=crop&w=1600&q=80',
    days: 8,
    fromPrice: 5400,
    accent: 'forest',
  },
  {
    id: 'santorini',
    name: 'Santorini',
    country: 'Greece',
    region: 'Europe',
    tagline: 'White-washed cliffs above an impossible blue.',
    coords: { lat: 36.3932, lon: 25.4615 },
    color: '#d9c397',
    image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1600&q=80',
    days: 6,
    fromPrice: 4200,
    accent: 'sand',
  },
  {
    id: 'banff',
    name: 'Banff',
    country: 'Canada',
    region: 'North America',
    tagline: 'Turquoise lakes cradled by Rocky Mountain stone.',
    coords: { lat: 51.4968, lon: -115.9281 },
    color: '#4f9472',
    image: 'https://images.unsplash.com/photo-1609825488888-3a766db05542?auto=format&fit=crop&w=1600&q=80',
    days: 10,
    fromPrice: 6100,
    accent: 'forest',
  },
]

export const tours = [
  {
    id: 'silk-road',
    title: 'The Silk Road Reverie',
    summary: '21 days through Uzbekistan, Kyrgyzstan and the high plateaus of Tajikistan.',
    days: 21,
    fromPrice: 12400,
    rating: 4.9,
    pace: 'Considered',
    image: 'https://images.unsplash.com/photo-1602002418082-a4443e081dd1?auto=format&fit=crop&w=1600&q=80',
    badge: 'Signature',
  },
  {
    id: 'norse-light',
    title: 'Norse Light, Northern Skies',
    summary: 'Norway’s fjords by sea, then northward to chase the aurora over Tromsø.',
    days: 11,
    fromPrice: 8900,
    rating: 4.8,
    pace: 'Slow',
    image: 'https://images.unsplash.com/photo-1483683804023-6ccdb62f86ef?auto=format&fit=crop&w=1600&q=80',
    badge: 'New',
  },
  {
    id: 'sahara-sands',
    title: 'Sahara Sands & Atlas Stone',
    summary: 'Marrakech to the Erg Chebbi dunes via mountain villages and kasbahs.',
    days: 9,
    fromPrice: 5400,
    rating: 4.9,
    pace: 'Active',
    image: 'https://images.unsplash.com/photo-1489493585363-d69421e0edd3?auto=format&fit=crop&w=1600&q=80',
    badge: 'Bestseller',
  },
  {
    id: 'andes-edge',
    title: 'Andes Edge Expedition',
    summary: 'Cusco, Sacred Valley, then four days on a private trail to Machu Picchu.',
    days: 13,
    fromPrice: 9200,
    rating: 4.95,
    pace: 'Active',
    image: 'https://images.unsplash.com/photo-1526392060635-9d6019884377?auto=format&fit=crop&w=1600&q=80',
    badge: 'Signature',
  },
]

export const testimonials = [
  {
    quote: 'Panda choreographed the kind of trip that quietly rearranges the way you see things. Every day felt deliberate.',
    author: 'Amelia Hart',
    role: 'Architect, London',
  },
  {
    quote: 'I have travelled with the big names. None of them came close to the texture and intimacy Panda built into our two weeks.',
    author: 'Daniel Okafor',
    role: 'Photographer, Lagos',
  },
  {
    quote: 'It felt less like an itinerary and more like a long letter from a friend who knew exactly where to take us.',
    author: 'Mei Tanaka',
    role: 'Editor, Tokyo',
  },
]

export const stats = [
  { value: 86, suffix: '+', label: 'Countries shaped' },
  { value: 12, suffix: 'k', label: 'Travellers guided' },
  { value: 4.96, suffix: '/5', label: 'Returning rating' },
  { value: 19, suffix: 'yr', label: 'Of crafted journeys' },
]
